### ISSUE TITLE
python3.6以上兼容问题

### ISSUE THREAD

**Issue by lhdlhdlhdhh** [hustcc/webhookit#16]
python3兼容：https://github.com/lenghonglin/webhookit/commit/f6e034bbad6a789df94b0e649137437eb2e86512
python3.6↑：rename line 35:  'async'->'async_...'  and line 139  :@'async'->'async_...'

**Comment by 18438655078** [comment]
改了之后支持3.6以上地址：https://github.com/18438655078/webhookit3
