### ISSUE TITLE
请问怎么配置repo_name，命名空间写在哪？

### ISSUE THREAD

**Issue by joindn** [hustcc/webhookit#6]
例如：https://github.com/hustcc/webhookit.git
我理解hustcc是命名空间，webhookit是项目名吧，命名空间在哪里配置？

**Comment by hustcc** [comment]
是的，你的理解是对的。

**Comment by joindn** [comment]
我的问题是命名空间在哪里配置呢？

**Comment by hustcc** [comment]
请看readme文件内容！

**Comment by joindn** [comment]
gitlab：git@git.51baomu.cn:wycode/shoprelease.git
我是按照说明配置的，配置文件如下：
`root@shoptest:~# cat /usr/shopxx/soft/webhook-configs/update.py 
# -*- coding: utf-8 -*-
'''
Created on Sep-17-17 14:31:20

@author: hustcc/webhookit
'''


# This means:
# When get a webhook request from `repo_name` on branch `branch_name`,
# will exec SCRIPT on servers config in the array.
WEBHOOKIT_CONFIGURE = {
    # a web hook request can trigger multiple servers.
    'shop/master': [{
        # if exec shell on local server, keep empty.
        'HOST': '',  # will exec shell on which server.
        'PORT': '',  # ssh port, default is 22.
        'USER': '',  # linux user name
        'PWD': '',  # user password or private key.

        # The webhook shell script path.
        'SCRIPT': '/usr/shopxx/soft/webhook-configs/test.sh'
    }],
    'wycode/shop': [{
        'SCRIPT': '/usr/shopxx/soft/webhook-configs/test.sh'
    }]
}`

**Comment by hustcc** [comment]
是这么配置，然后运行webhookit的时候指定这个配置文件。

**Comment by joindn** [comment]
WEBHOOK logs

17-09-26 14:35:38.527420: Not match the repo and branch or the webhook servers is not exist: /

**Comment by joindn** [comment]
截图：
https://pan.baidu.com/s/1kUPSSLp
https://pan.baidu.com/s/1c2jefNa
https://pan.baidu.com/s/1hrPZbRA

**Comment by hustcc** [comment]
修改配置文件之后，重新启动 webhookit！

**Comment by joindn** [comment]
重启过了

**Comment by joindn** [comment]
重启过了

**Comment by joindn** [comment]
http://pan.baidu.com/s/1nv1I8Pj

**Comment by hustcc** [comment]
运行之后，打开网页，看看网页上显示的配置是不是和你写的一致！

**Comment by joindn** [comment]
完全一致，测试用的是shop/master

**Comment by joindn** [comment]
http://pan.baidu.com/s/1qXPIKsk

**Comment by joindn** [comment]
请问这若不是配置问题，那是哪里出了问题呢？

**Comment by joindn** [comment]
17-09-26 18:23:27.080341: Starting to execute /usr/shopxx/soft/webhook-configs/test.sh
17-09-26 18:23:27.080838: Start to process server: {"PORT": "****", "PWD": "*******", "HOST": "***.**.**.**", "USER": "*******", "SCRIPT": "/usr/shopxx/soft/webhook-configs/test.sh"}
17-09-26 18:23:27.081016: Start to execute remote SSH command. /usr/shopxx/soft/webhook-configs/test.sh
[I 170926 18:23:27 web:2063] 200 POST /webhookit (127.0.0.1) 2.06ms
[I 170926 18:23:27 transport:1685] Connected (version 2.0, client OpenSSH_7.2p2)
17-09-26 18:23:27.161155: Not match the repo and branch or the webhook servers is not exist: /
[I 170926 18:23:27 web:2063] 200 POST /webhookit (127.0.0.1) 1.02ms
[I 170926 18:23:27 transport:1685] Authentication (password) successful!
17-09-26 18:23:27.468147: Completed execute: (True, )

还是报Not match the repo and branch or the webhook servers is not exist: /

**Comment by hustcc** [comment]
第一行不是已经执行了脚本吗？

另外一个可能是你 push 到非 master 分支！

**Comment by joindn** [comment]
push的是master分支，而且这里输出的日志确实显示是执行了，但也仅仅是显示，并未真的执行

**Comment by joindn** [comment]
`{
  "object_kind": "push",
  "event_name": "push",
  "before": "14ef4425b5e443ee54c99b26873a9d82d7bd4b1f",
  "after": "6935799e36790b3416e6312d5e6715ef13e6b991",
  "ref": "refs/heads/master",
  "checkout_sha": "6935799e36790b3416e6312d5e6715ef13e6b991",
  "message": null,
  "user_id": 2,
  "user_name": "商城开发",
  "user_username": "zengjindong",
  "user_email": "2850393594@qq.com",
  "user_avatar": "http://www.gravatar.com/avatar/12e2fb29eaf55dedcd52a186280a1ad2?s=80&d=identicon",
  "project_id": 18,
  "project": {
    "name": "shop",
    "description": "",
    "web_url": "http://git.51baomu.cn/wycode/shop",
    "avatar_url": null,
    "git_ssh_url": "git@git.51baomu.cn:wycode/shop.git",
    "git_http_url": "http://git.51baomu.cn/wycode/shop.git",
    "namespace": "无忧代码库",
    "visibility_level": 0,
    "path_with_namespace": "wycode/shop",
    "default_branch": "master",
    "ci_config_path": null,
    "homepage": "http://git.51baomu.cn/wycode/shop",
    "url": "git@git.51baomu.cn:wycode/shop.git",
    "ssh_url": "git@git.51baomu.cn:wycode/shop.git",
    "http_url": "http://git.51baomu.cn/wycode/shop.git"
  },
  "commits": [
    {
      "id": "6935799e36790b3416e6312d5e6715ef13e6b991",
      "message": "aa\n",
      "timestamp": "2017-09-27T09:18:30+08:00",
      "url": "http://git.51baomu.cn/wycode/shop/commit/6935799e36790b3416e6312d5e6715ef13e6b991",
      "author": {
        "name": "zengjindong",
        "email": "2850393594@qq.com"
      },
      "added": [

      ],
      "modified": [
        "23"
      ],
      "removed": [

      ]
    }
  ],
  "total_commits_count": 1,
  "repository": {
    "name": "shop",
    "url": "git@git.51baomu.cn:wycode/shop.git",
    "description": "",
    "homepage": "http://git.51baomu.cn/wycode/shop",
    "git_http_url": "http://git.51baomu.cn/wycode/shop.git",
    "git_ssh_url": "git@git.51baomu.cn:wycode/shop.git",
    "visibility_level": 0
  }
}`

**Comment by joindn** [comment]
root@shoptest:/usr/shopxx/soft/webhook-configs# ll test.sh 
-rwxr-xr-x 1 root root 39 Sep 26 18:23 test.sh*
root@shoptest:/usr/shopxx/soft/webhook-configs# cat test.sh 
touch sss.log
echo "123" >> ./test.log

**Comment by joindn** [comment]
日志显示是执行了，test.sh 脚本权限是755，属于root用户组
root@shoptest:/usr/shopxx/soft/webhook-configs#  ll test.sh 
-rwxr-xr-x 1 root root 39 Sep 26 18:23 test.sh*
内容如下：
root@shoptest:/usr/shopxx/soft/webhook-configs# cat test.sh 
touch sss.log
echo "123" >> ./test.log
但是没有创建 sss.log文件，或写入test.log日志，麻烦帮忙看看咋回事

**Comment by hustcc** [comment]
cat test.log是相对路径，写成绝对路径看看。

**Comment by joindn** [comment]
可以了，是我反二了哈哈，谢谢~~
-rw-r--r-- 1 root root  141 Sep 26 16:56 update.py
root@shoptest:/usr/shopxx/soft/webhook-configs# cat test.sh 
touch /usr/shopxx/soft/webhook-configs/sss.log
echo "123" >> /usr/shopxx/soft/webhook-configs/test.log

**Comment by hustcc** [comment]
😢
