### ISSUE TITLE
tag push时貌似有点儿问题

### ISSUE THREAD

**Issue by nmshuishui** [hustcc/webhookit#8]
当绑定gitlab的tag push evets的时候，会把repo/branch中的branch替换为tag名称。
创建tag：git tag -a v1.0 -m "first tag version"
tag提交命令：git push origin --tags

在返回的Response body中，就会报错：{"data": "Not match the repo and branch or the webhook servers is not exist: cmdb/v1.0", "success": false}

**Comment by hustcc** [comment]
tag 不是分支，目前仅仅支持分支！
